PROJECT = relay

DEPS = cowboy erlport jsonerl
dep_cowboy = pkg://cowboy master
dep_erlport = https://github.com/hdima/erlport.git master
dep_jsonerl = https://github.com/lambder/jsonerl.git master

include erlang.mk
